{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aivo-service.fullname" . }}
  namespace: aivo-monitoring
  labels:
    {{- include "aivo-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aivo-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - aivo-services
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
