# Kong declarative configuration for aivo-virtual-brains
# S0-08 API Edge Gateway with security, custom plugins, and service mesh

_format_version: "3.0"
_transform: true

# Services Configuration
services:
  # Apollo Router - GraphQL Federation
  - name: apollo-router
    url: http://apollo-router:4000
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: graphql-endpoint
        paths:
          - /graphql
        methods:
          - GET
          - POST
          - OPTIONS
        strip_path: false
        preserve_host: false
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "https://*.aivo.ai"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Content-Type
            - Authorization
            - X-Correlation-ID
            - X-Learner-Scope
          exposed_headers:
            - X-Correlation-ID
            - X-Request-ID
          credentials: true
          max_age: 3600
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid#counter
          echo_downstream: true

  # Authentication Service (Placeholder)
  - name: auth-svc
    url: http://auth-service:8080
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    routes:
      - name: auth-routes
        paths:
          - /auth
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        strip_path: true
        preserve_host: false
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "https://*.aivo.ai"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Content-Type
            - Authorization
            - X-Correlation-ID
          credentials: true
          max_age: 3600
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid#counter
          echo_downstream: true
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
          policy: local
          hide_client_headers: false

  # User Service (Placeholder)
  - name: user-svc
    url: http://user-service:8080
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    routes:
      - name: user-routes
        paths:
          - /users
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        strip_path: true
        preserve_host: false
    plugins:
      - name: jwt
        config:
          uri_param_names:
            - token
          cookie_names:
            - jwt
          header_names:
            - Authorization
          key_claim_name: iss
          secret_is_base64: false
          run_on_preflight: false
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "https://*.aivo.ai"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Content-Type
            - Authorization
            - X-Correlation-ID
            - X-Learner-Scope
          credentials: true
          max_age: 3600
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid#counter
          echo_downstream: true
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
          policy: local
          hide_client_headers: false
      # Custom plugin stub: Learner Scope Validation
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Plugin-Learner-Scope: enabled"
      - name: acl
        config:
          allow:
            - learner
            - admin
            - instructor

  # Gateway Health Check
  - name: gateway-health
    url: http://httpbin.org/status/200
    routes:
      - name: gateway-health-check
        paths:
          - /gateway/health
        methods:
          - GET
        strip_path: true
        preserve_host: false
    plugins:
      - name: response-transformer
        config:
          replace:
            json:
              - "status:healthy"
              - "service:aivo-gateway"
              - "timestamp:`date`"
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid#counter
          echo_downstream: true

# Global Plugins Configuration
plugins:
  # Global CORS for all services
  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "http://localhost:4000"
        - "https://*.aivo.ai"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      headers:
        - Content-Type
        - Authorization
        - X-Correlation-ID
        - X-Learner-Scope
        - X-Dashboard-Context
      exposed_headers:
        - X-Correlation-ID
        - X-Request-ID
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
      credentials: true
      max_age: 3600
      preflight_continue: false

  # Global Prometheus Metrics
  - name: prometheus
    config:
      per_consumer: false
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  # Global Request/Response Logging
  - name: file-log
    config:
      path: /dev/stdout
      reopen: true

# Consumers (JWT Issuers)
consumers:
  - username: aivo-web-app
    custom_id: web-app-001
    tags:
      - web-client
    jwt_secrets:
      - key: aivo-web-key
        algorithm: HS256
        secret: dev-secret-key-change-in-production
    plugins:
      - name: rate-limiting
        config:
          minute: 300
          hour: 3000
          policy: local
      - name: acl
        config:
          allow:
            - learner
            - admin
            - instructor
      # Custom plugin stubs
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Plugin-Dash-Context: enabled"
              - "X-Plugin-Consent-Gate: enabled"

  - username: aivo-mobile-app
    custom_id: mobile-app-001
    tags:
      - mobile-client
    jwt_secrets:
      - key: aivo-mobile-key
        algorithm: HS256
        secret: dev-mobile-secret-key-change-in-production
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 5000
          policy: local
      - name: acl
        config:
          allow:
            - learner
# ACL Group Assignments for Role-Based Access
# Note: ACLs are configured per consumer via plugins above

# Custom Plugin Configurations (Config-Only Stubs)
# These represent the custom plugins that would be implemented:
# 1. dash_context: Dashboard context injection
# 2. learner_scope: Learning scope validation
# 3. consent_gate: Privacy consent enforcement
#
# For now, these are simulated using request-transformer + ACL
# In production, these would be proper Kong Lua plugins
