# OpenTelemetry Collector configuration for aivo-virtual-brains

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:4000"

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          static_configs:
            - targets: ["localhost:8888"]
        - job_name: "kong"
          static_configs:
            - targets: ["kong:8001"]
          metrics_path: "/metrics"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  # Attribute processor to ensure privacy compliance
  attributes:
    actions:
      # Privacy compliance - remove any PII
      - key: user.email
        action: delete
      - key: user.name
        action: delete
      - key: user.phone
        action: delete
      - key: user.address
        action: delete
      # Standard environment attribute
      - key: environment
        value: "development"
        action: insert
      # Ensure service instance ID is present
      - key: service.instance.id
        from_attribute: host.name
        action: upsert

  # Resource processor to add standard attributes
  resource:
    attributes:
      - key: deployment.environment
        value: "${env:ENVIRONMENT}"
        action: upsert
      - key: service.namespace
        value: "aivo-virtual-brains"
        action: upsert

  resourcedetection:
    detectors: [env, system, docker]
    timeout: 2s
    override: false

exporters:
  # Jaeger for traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Loki for logs
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Debug exporter for development
  debug:
    verbosity: basic

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, attributes, batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: [resourcedetection, attributes, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [resourcedetection, attributes, batch]
      exporters: [loki, debug]

  extensions: []
