# OpenTelemetry Collector configuration for aivo-virtual-brains

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:4000"

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          static_configs:
            - targets: ["localhost:8888"]
        - job_name: "kong"
          static_configs:
            - targets: ["kong:8001"]
          metrics_path: "/metrics"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resourcedetection:
    detectors: [env, system, docker]
    timeout: 2s
    override: false

  attributes:
    actions:
      - key: environment
        value: "development"
        action: insert
      - key: service.instance.id
        from_attribute: host.name
        action: insert

exporters:
  # Jaeger for traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Loki for logs
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Debug exporter for development
  debug:
    verbosity: basic

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, attributes, batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: [resourcedetection, attributes, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [resourcedetection, attributes, batch]
      exporters: [loki, debug]

  extensions: []
