apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollouts.argoproj.io
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: aivo-platform
spec:
  group: argoproj.io
  names:
    kind: Rollout
    listKind: RolloutList
    plural: rollouts
    singular: rollout
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.selector
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - selector
                - template
              properties:
                replicas:
                  type: integer
                  format: int32
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                template:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                    spec:
                      type: object
                strategy:
                  type: object
                  properties:
                    canary:
                      type: object
                      properties:
                        steps:
                          type: array
                          items:
                            type: object
                        maxSurge:
                          anyOf:
                            - type: integer
                            - type: string
                        maxUnavailable:
                          anyOf:
                            - type: integer
                            - type: string
                        analysis:
                          type: object
                          properties:
                            templates:
                              type: array
                              items:
                                type: object
                            args:
                              type: array
                              items:
                                type: object
                        trafficRouting:
                          type: object
                          properties:
                            nginx:
                              type: object
                            istio:
                              type: object
                            smi:
                              type: object
                    blueGreen:
                      type: object
                      properties:
                        activeService:
                          type: string
                        previewService:
                          type: string
                        autoPromotionEnabled:
                          type: boolean
                        scaleDownDelaySeconds:
                          type: integer
                        prePromotionAnalysis:
                          type: object
                        postPromotionAnalysis:
                          type: object
                revisionHistoryLimit:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
                updatedReplicas:
                  type: integer
                  format: int32
                readyReplicas:
                  type: integer
                  format: int32
                availableReplicas:
                  type: integer
                  format: int32
                observedGeneration:
                  type: integer
                  format: int64
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastUpdateTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                selector:
                  type: string
                currentPodHash:
                  type: string
                stablePodHash:
                  type: string
                phase:
                  type: string
                message:
                  type: string
      additionalPrinterColumns:
        - name: Desired
          type: integer
          description: Number of desired pods
          jsonPath: .spec.replicas
        - name: Current
          type: integer
          description: Number of current pods
          jsonPath: .status.replicas
        - name: Up-to-date
          type: integer
          description: Number of up-to-date pods
          jsonPath: .status.updatedReplicas
        - name: Available
          type: integer
          description: Number of available pods
          jsonPath: .status.availableReplicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analysistemplates.argoproj.io
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: aivo-platform
spec:
  group: argoproj.io
  names:
    kind: AnalysisTemplate
    listKind: AnalysisTemplateList
    plural: analysistemplates
    singular: analysistemplate
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metrics:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      provider:
                        type: object
                        properties:
                          prometheus:
                            type: object
                          datadog:
                            type: object
                          wavefront:
                            type: object
                          newrelic:
                            type: object
                          job:
                            type: object
                          web:
                            type: object
                      interval:
                        type: string
                      count:
                        type: integer
                      successCondition:
                        type: string
                      failureCondition:
                        type: string
                      failureLimit:
                        type: integer
                      inconclusiveLimit:
                        type: integer
                      consecutiveErrorLimit:
                        type: integer
                args:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
            status:
              type: object
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analysisruns.argoproj.io
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: aivo-platform
spec:
  group: argoproj.io
  names:
    kind: AnalysisRun
    listKind: AnalysisRunList
    plural: analysisruns
    singular: analysisrun
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metrics:
                  type: array
                  items:
                    type: object
                args:
                  type: array
                  items:
                    type: object
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                metricResults:
                  type: array
                  items:
                    type: object
                runSummary:
                  type: object
      additionalPrinterColumns:
        - name: Status
          type: string
          description: Analysis status
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
