/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Auth Service API
 * Authentication service for Aivo Virtual Brains
 * OpenAPI spec version: 1.0.0
 */

export type LoginBody = {
  email: string;
  password: string;
};
