/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { OrchestrationAction } from "./orchestrationAction";
import type { ActionListFiltersApplied } from "./actionListFiltersApplied";

export interface ActionList {
  actions?: OrchestrationAction[];
  total_count?: number;
  has_more?: boolean;
  filters_applied?: ActionListFiltersApplied;
}
