/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export type HealthResponseStatus =
  (typeof HealthResponseStatus)[keyof typeof HealthResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseStatus = {
  healthy: "healthy",
  degraded: "degraded",
  unhealthy: "unhealthy",
} as const;
