/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseComponentsEventConsumer } from "./healthResponseComponentsEventConsumer";
import type { HealthResponseComponentsOrchestrationEngine } from "./healthResponseComponentsOrchestrationEngine";
import type { HealthResponseComponentsRedisConnection } from "./healthResponseComponentsRedisConnection";
import type { HealthResponseComponentsServiceClients } from "./healthResponseComponentsServiceClients";

export type HealthResponseComponents = {
  event_consumer?: HealthResponseComponentsEventConsumer;
  orchestration_engine?: HealthResponseComponentsOrchestrationEngine;
  redis_connection?: HealthResponseComponentsRedisConnection;
  service_clients?: HealthResponseComponentsServiceClients;
};
