/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseStatus } from "./healthResponseStatus";
import type { HealthResponseComponents } from "./healthResponseComponents";

export interface HealthResponse {
  status?: HealthResponseStatus;
  timestamp?: string;
  version?: string;
  components?: HealthResponseComponents;
}
