/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { LearnerOrchestrationStateSelAlertsItemData } from "./learnerOrchestrationStateSelAlertsItemData";

export type LearnerOrchestrationStateSelAlertsItem = {
  timestamp?: string;
  alert_type?: string;
  severity?: string;
  data?: LearnerOrchestrationStateSelAlertsItemData;
};
