/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export type LearnerOrchestrationStateCurrentLevel =
  (typeof LearnerOrchestrationStateCurrentLevel)[keyof typeof LearnerOrchestrationStateCurrentLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LearnerOrchestrationStateCurrentLevel = {
  beginner: "beginner",
  easy: "easy",
  moderate: "moderate",
  challenging: "challenging",
  advanced: "advanced",
} as const;
