/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export type LearnerOrchestrationStateRecentAssessmentsItem = {
  timestamp?: string;
  score?: number;
  percentile?: number;
  assessment_type?: string;
};
