/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { LearnerOrchestrationStateCurrentLevel } from "./learnerOrchestrationStateCurrentLevel";
import type { LearnerOrchestrationStateSelAlertsItem } from "./learnerOrchestrationStateSelAlertsItem";
import type { LearnerOrchestrationStateSlpData } from "./learnerOrchestrationStateSlpData";
import type { LearnerOrchestrationStateRecentAssessmentsItem } from "./learnerOrchestrationStateRecentAssessmentsItem";

export interface LearnerOrchestrationState {
  learner_id?: string;
  tenant_id?: string;
  current_level?: LearnerOrchestrationStateCurrentLevel;
  /**
   * @minimum 0
   * @maximum 1
   */
  engagement_score?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  performance_score?: number;
  consecutive_correct?: number;
  consecutive_incorrect?: number;
  session_duration_minutes?: number;
  break_due_time?: string;
  last_break_time?: string;
  sel_alerts?: LearnerOrchestrationStateSelAlertsItem[];
  baseline_established?: boolean;
  slp_data?: LearnerOrchestrationStateSlpData;
  recent_assessments?: LearnerOrchestrationStateRecentAssessmentsItem[];
  updated_at?: string;
}
