/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { ListEventsEventType } from "./listEventsEventType";

export type ListEventsParams = {
  learner_id?: string;
  event_type?: ListEventsEventType;
  start_date?: string;
  end_date?: string;
  /**
   * @maximum 200
   */
  limit?: number;
  offset?: number;
};
