/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export type OrchestrationEventType =
  (typeof OrchestrationEventType)[keyof typeof OrchestrationEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrchestrationEventType = {
  BASELINE_COMPLETE: "BASELINE_COMPLETE",
  SLP_UPDATED: "SLP_UPDATED",
  SEL_ALERT: "SEL_ALERT",
  COURSEWORK_ANALYZED: "COURSEWORK_ANALYZED",
  ASSESSMENT_COMPLETE: "ASSESSMENT_COMPLETE",
  LEARNER_PROGRESS: "LEARNER_PROGRESS",
  ENGAGEMENT_LOW: "ENGAGEMENT_LOW",
} as const;
