/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export type OrchestrationActionType =
  (typeof OrchestrationActionType)[keyof typeof OrchestrationActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrchestrationActionType = {
  LEVEL_SUGGESTED: "LEVEL_SUGGESTED",
  GAME_BREAK: "GAME_BREAK",
  SEL_INTERVENTION: "SEL_INTERVENTION",
  LEARNING_PATH_UPDATE: "LEARNING_PATH_UPDATE",
} as const;
