/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { OrchestrationActionType } from "./orchestrationActionType";
import type { OrchestrationActionActionData } from "./orchestrationActionActionData";
import type { OrchestrationActionStatus } from "./orchestrationActionStatus";

export interface OrchestrationAction {
  id?: string;
  type?: OrchestrationActionType;
  target_service?: string;
  learner_id?: string;
  tenant_id?: string;
  action_data?: OrchestrationActionActionData;
  status?: OrchestrationActionStatus;
  created_at?: string;
  executed_at?: string;
  error_message?: string;
}
