/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */

export interface OrchestrationStats {
  total_events_processed?: number;
  level_suggestions_sent?: number;
  game_breaks_scheduled?: number;
  sel_interventions_triggered?: number;
  learning_path_updates?: number;
  active_learners?: number;
  is_initialized?: boolean;
  uptime_seconds?: number;
  last_event_processed_at?: string;
}
