/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { OrchestrationEventType } from "./orchestrationEventType";
import type { OrchestrationEventData } from "./orchestrationEventData";

export interface OrchestrationEvent {
  id?: string;
  type?: OrchestrationEventType;
  learner_id?: string;
  tenant_id?: string;
  timestamp?: string;
  data?: OrchestrationEventData;
  processed_at?: string;
  actions_generated?: number;
}
