/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { OrchestrationAction } from "./orchestrationAction";

export interface TriggerEventResponse {
  event_id?: string;
  actions_generated?: OrchestrationAction[];
  processing_time_ms?: number;
}
