/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Orchestrator Service API
 * Event-driven orchestration service for intelligent level suggestions and game break triggers
 * OpenAPI spec version: 1.0.0
 */
import type { TriggerEventRequestType } from "./triggerEventRequestType";
import type { TriggerEventRequestData } from "./triggerEventRequestData";

export interface TriggerEventRequest {
  type: TriggerEventRequestType;
  learner_id: string;
  tenant_id: string;
  data: TriggerEventRequestData;
}
