version: "3.8"

services:
  config-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - DEBUG=false
    depends_on:
      - redis
    volumes:
      - ./app:/app/app # For development hot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
