/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Notification Service API
 * Real-time notification service with WebSocket hub, push subscriptions, and daily digest functionality.

## Features
- **WebSocket Hub**: Real-time notification delivery via WebSocket connections
- **Push Subscriptions**: Browser push notifications with Web Push API
- **Daily Digest**: Automated daily summary notifications
- **Multi-channel Delivery**: Support for WebSocket, push, email, and in-app notifications
- **Real-time Collaboration**: 1-to-N message fanout for collaborative features

## Authentication
All endpoints require JWT authentication via the `Authorization` header:
```
Authorization: Bearer <jwt_token>
```

## WebSocket Connection
Connect to real-time notifications via WebSocket:
```
wss://api.aivo.ai/notification-svc/ws/notify?token=<jwt_token>
```

 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { DigestSubscription, DigestSubscriptionUpdate } from "../../types";

export const getDailyDigest = () => {
  /**
   * Get current user's daily digest subscription settings
   * @summary Get digest subscription
   */
  const getApiV1DigestSubscription = <
    TData = AxiosResponse<DigestSubscription>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/v1/digest/subscription`, options);
  };
  /**
   * Update daily digest preferences for the current user
   * @summary Update digest subscription
   */
  const putApiV1DigestSubscription = <TData = AxiosResponse<null>>(
    digestSubscriptionUpdate: DigestSubscriptionUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios
      .put(`/api/v1/digest/subscription`, digestSubscriptionUpdate, options)
      .then((res) => {
        if (res.data === "") res.data = null;
        return res as TData;
      });
  };
  return { getApiV1DigestSubscription, putApiV1DigestSubscription };
};
export type GetApiV1DigestSubscriptionResult =
  AxiosResponse<DigestSubscription>;
export type PutApiV1DigestSubscriptionResult = AxiosResponse<null>;
