/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Search Service API
 * OpenSearch-powered search and suggestion service with role-based access control.

## Overview

The AIVO Search Service provides comprehensive full-text search capabilities across
educational documents including IEPs, assessments, student records, and curriculum
resources. All search operations enforce role-based access control (RBAC) to ensure
users only access data they're authorized to view.

## Authentication

All endpoints require JWT authentication via the `Authorization: Bearer <token>` header.
The JWT token must contain:
- `sub`: User ID
- `tenant_id`: Tenant identifier  
- `roles`: Array of user roles
- `school_ids`: Array of accessible school IDs
- `student_ids`: Array of accessible student IDs (for parents)

## Role-Based Access Control

Access to search results is filtered based on user roles:

- **System Admin**: Access to all data across all tenants
- **Tenant Admin**: Access to all data within their tenant
- **School Admin**: Access to data within their assigned schools
- **Teacher**: Access to student data within their schools
- **Case Manager**: Access to IEPs and assessments within their schools
- **Parent**: Access to their children's IEPs and assessments only
- **Student**: Access to their own IEP data only

## Document Types

- `iep`: Individual Education Programs
- `assessment`: Psychological and educational assessments
- `student`: Student profile information
- `curriculum`: Curriculum standards and learning objectives
- `resource`: Educational resources and materials

 * OpenAPI spec version: 1.0.0
 */
import type { SearchResultDocumentType } from './searchResultDocumentType';
import type { SearchResultHighlight } from './searchResultHighlight';
import type { SearchResultMetadata } from './searchResultMetadata';

export interface SearchResult {
  /** Unique document identifier */
  id: string;
  /** Document title */
  title: string;
  /** Document content (truncated) */
  content: string;
  /** Type of document */
  document_type: SearchResultDocumentType;
  /** Tenant identifier */
  tenant_id: string;
  /**
   * School identifier
   * @nullable
   */
  school_id?: string | null;
  /**
   * Document creation timestamp
   * @nullable
   */
  created_at?: string | null;
  /**
   * Document update timestamp
   * @nullable
   */
  updated_at?: string | null;
  /**
   * Search relevance score
   * @nullable
   */
  score?: number | null;
  /**
   * Highlighted search terms
   * @nullable
   */
  highlight?: SearchResultHighlight;
  /**
   * Additional document metadata
   * @nullable
   */
  metadata?: SearchResultMetadata;
}
