apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-gateway-svc
  namespace: argocd
  labels:
    app.kubernetes.io/name: inference-gateway-svc
    app.kubernetes.io/part-of: aivo-platform
    app.kubernetes.io/component: service
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aivo-ai/aivo-virtual-brain.git
    targetRevision: HEAD
    path: infra/helm/services/inference-gateway-svc
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: production
        - name: vault.role
          value: inference-gateway-svc
        - name: image.tag
          value: latest
        - name: priorityClassName
          value: aivo-high
        - name: autoscaling.maxReplicas
          value: "20"
  destination:
    server: https://kubernetes.default.svc
    namespace: aivo-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: ""
      kind: "Secret"
      jsonPointers:
        - /data
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-*
