apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learner-ns-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: learner-ns-operator
    app.kubernetes.io/component: operator
    aivo.dev/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aivo-platform
  source:
    repoURL: https://github.com/aivo-virtual-brains/platform.git
    targetRevision: HEAD
    path: services/learner-ns-operator/charts/learner-ns-operator
    helm:
      values: |
        operator:
          namespace: aivo-system
          logLevel: INFO
          defaultResourceQuota:
            cpu: "2"
            memory: "4Gi"
            storage: "10Gi"
            pods: 10
          defaultNetworkPolicy:
            egressDeny: true
            allowedNamespaces:
              - "aivo-system"
              - "aivo-shared"
          defaultVaultRole: "learner-default"
        
        image:
          repository: aivo/learner-ns-operator
          tag: "1.0.0"
          pullPolicy: IfNotPresent
        
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        monitoring:
          enabled: true
          serviceMonitor:
            enabled: true
        
        crd:
          install: true
          upgrade: false
        
        podAnnotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "learner-ns-operator"
          vault.hashicorp.com/agent-inject-secret-config: "secret/data/operators/learner-ns"
  destination:
    server: https://kubernetes.default.svc
    namespace: aivo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false  # Namespace managed by platform chart
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: learnerspaces.aivo.dev
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status
