apiVersion: v2
name: aivo-platform
description: AIVO Virtual Brains Platform Infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - education
  - ai
  - kubernetes
  - platform

maintainers:
  - name: AIVO Platform Team
    email: platform@aivo.dev

dependencies:
  - name: prometheus
    version: "15.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.50.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    version: "4.4.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
