/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * Assessment subject
 */
export type AdaptiveStartRequestSubject =
  (typeof AdaptiveStartRequestSubject)[keyof typeof AdaptiveStartRequestSubject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdaptiveStartRequestSubject = {
  math: "math",
  reading: "reading",
  science: "science",
  social_studies: "social_studies",
  language_arts: "language_arts",
} as const;
