/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface AdaptiveAnswerResponse {
  session_id?: string;
  item_id?: string;
  is_correct?: boolean;
  /** Updated ability estimate */
  updated_theta?: number;
  /** Standard error of ability estimate */
  standard_error?: number;
  /** Whether assessment is complete */
  is_complete?: boolean;
  timestamp?: string;
}
