/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AdaptiveAnswerRequestResponse } from "./adaptiveAnswerRequestResponse";

export interface AdaptiveAnswerRequest {
  /** Assessment session ID */
  session_id: string;
  /** Assessment item ID */
  item_id: string;
  /** Learner response */
  response: AdaptiveAnswerRequestResponse;
  /** Response time in milliseconds */
  response_time_ms?: number;
}
