/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AdaptiveStartResponseStatus } from "./adaptiveStartResponseStatus";

export interface AdaptiveStartResponse {
  /** Assessment session ID */
  session_id?: string;
  status?: AdaptiveStartResponseStatus;
  /** Initial ability estimate */
  initial_theta?: number;
  timestamp?: string;
}
