/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type AdaptiveStartResponseStatus =
  (typeof AdaptiveStartResponseStatus)[keyof typeof AdaptiveStartResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdaptiveStartResponseStatus = {
  active: "active",
  completed: "completed",
  error: "error",
} as const;
