/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AdaptiveStartRequestSubject } from "./adaptiveStartRequestSubject";
import type { AdaptiveStartRequestMetadata } from "./adaptiveStartRequestMetadata";

export interface AdaptiveStartRequest {
  /**
   * Learner identifier
   * @maxLength 100
   */
  learner_id: string;
  /**
   * Tenant identifier
   * @maxLength 100
   */
  tenant_id: string;
  /** Assessment subject */
  subject: AdaptiveStartRequestSubject;
  /** Additional session metadata */
  metadata?: AdaptiveStartRequestMetadata;
}
