/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { Assessment } from "./assessment";

export interface AssessmentList {
  assessments?: Assessment[];
  total_count?: number;
  has_more?: boolean;
}
