/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionAnalytics } from "./questionAnalytics";
import type { AssessmentAnalyticsSubjectScores } from "./assessmentAnalyticsSubjectScores";
import type { AssessmentAnalyticsCognitiveScores } from "./assessmentAnalyticsCognitiveScores";

export interface AssessmentAnalytics {
  /**
   * @minimum 0
   * @maximum 1
   */
  overall_score?: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  percentile_rank?: number;
  ability_estimate?: number;
  standard_error?: number;
  question_analytics?: QuestionAnalytics[];
  subject_scores?: AssessmentAnalyticsSubjectScores;
  cognitive_scores?: AssessmentAnalyticsCognitiveScores;
  strengths?: string[];
  challenges?: string[];
}
