/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type AssessmentQuestionQuestionType =
  (typeof AssessmentQuestionQuestionType)[keyof typeof AssessmentQuestionQuestionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssessmentQuestionQuestionType = {
  multiple_choice: "multiple_choice",
  short_answer: "short_answer",
  essay: "essay",
  true_false: "true_false",
} as const;
