/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentAssessmentType } from "./assessmentAssessmentType";
import type { AssessmentStatus } from "./assessmentStatus";
import type { AssessmentQuestion } from "./assessmentQuestion";
import type { AssessmentMetadata } from "./assessmentMetadata";

export interface Assessment {
  id?: string;
  tenant_id?: string;
  learner_id?: string;
  assessment_type?: AssessmentAssessmentType;
  title?: string;
  description?: string;
  status?: AssessmentStatus;
  questions?: AssessmentQuestion[];
  metadata?: AssessmentMetadata;
  created_at?: string;
  updated_at?: string;
  completed_at?: string;
}
