/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type AssessmentQuestionCognitiveLevel =
  (typeof AssessmentQuestionCognitiveLevel)[keyof typeof AssessmentQuestionCognitiveLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssessmentQuestionCognitiveLevel = {
  remember: "remember",
  understand: "understand",
  apply: "apply",
  analyze: "analyze",
  evaluate: "evaluate",
  create: "create",
} as const;
