/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentQuestionQuestionType } from "./assessmentQuestionQuestionType";
import type { AssessmentQuestionCognitiveLevel } from "./assessmentQuestionCognitiveLevel";

export interface AssessmentQuestion {
  id?: string;
  question_text?: string;
  question_type?: AssessmentQuestionQuestionType;
  options?: string[];
  correct_answer?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  difficulty?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  discrimination?: number;
  subject_area?: string;
  cognitive_level?: AssessmentQuestionCognitiveLevel;
}
