/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentReportResponseProficiencyLevel } from "./assessmentReportResponseProficiencyLevel";
import type { AssessmentReportResponsePerformanceSummary } from "./assessmentReportResponsePerformanceSummary";

export interface AssessmentReportResponse {
  session_id?: string;
  learner_id?: string;
  /** Final ability estimate */
  final_theta?: number;
  /** Final standard error */
  standard_error?: number;
  /** Mapped proficiency level */
  proficiency_level?: AssessmentReportResponseProficiencyLevel;
  /**
   * Confidence in level assignment
   * @minimum 0
   * @maximum 1
   */
  confidence_score?: number;
  /** Number of items administered */
  items_completed?: number;
  /** Total assessment time */
  total_time_ms?: number;
  performance_summary?: AssessmentReportResponsePerformanceSummary;
  completed_at?: string;
}
