/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mapped proficiency level
 */
export type AssessmentReportResponseProficiencyLevel =
  (typeof AssessmentReportResponseProficiencyLevel)[keyof typeof AssessmentReportResponseProficiencyLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssessmentReportResponseProficiencyLevel = {
  L0: "L0",
  L1: "L1",
  L2: "L2",
  L3: "L3",
  L4: "L4",
} as const;
