/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type AssessmentStatus =
  (typeof AssessmentStatus)[keyof typeof AssessmentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssessmentStatus = {
  draft: "draft",
  active: "active",
  completed: "completed",
  archived: "archived",
} as const;
