/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type AssessmentAssessmentType =
  (typeof AssessmentAssessmentType)[keyof typeof AssessmentAssessmentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssessmentAssessmentType = {
  baseline: "baseline",
  progress: "progress",
  diagnostic: "diagnostic",
  summative: "summative",
} as const;
