/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface AssessmentResponse {
  question_id: string;
  answer: string;
  response_time_ms?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence_level?: number;
}
