/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface BaselineResult {
  assessment_id?: string;
  overall_score?: number;
  percentile?: number;
  strengths?: string[];
  challenges?: string[];
  recommended_level?: string;
  event_published?: boolean;
  event_id?: string;
}
