/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface CreateBaselineRequest {
  tenant_id: string;
  learner_id: string;
  grade_level?: string;
  subject_areas?: string[];
}
