/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAssessmentRequestAssessmentType } from "./createAssessmentRequestAssessmentType";
import type { AssessmentQuestion } from "./assessmentQuestion";
import type { CreateAssessmentRequestMetadata } from "./createAssessmentRequestMetadata";

export interface CreateAssessmentRequest {
  tenant_id: string;
  learner_id: string;
  assessment_type: CreateAssessmentRequestAssessmentType;
  title: string;
  description?: string;
  questions?: AssessmentQuestion[];
  metadata?: CreateAssessmentRequestMetadata;
}
