/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseStatus } from "./healthResponseStatus";
import type { HealthResponseComponents } from "./healthResponseComponents";

export interface HealthResponse {
  status?: HealthResponseStatus;
  timestamp?: string;
  version?: string;
  components?: HealthResponseComponents;
}
