/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { ItemCalibrationResponsePreviousParameters } from "./itemCalibrationResponsePreviousParameters";
import type { ItemCalibrationResponseNewParameters } from "./itemCalibrationResponseNewParameters";
import type { ItemCalibrationResponseFitStatistics } from "./itemCalibrationResponseFitStatistics";

export interface ItemCalibrationResponse {
  item_id?: string;
  previous_parameters?: ItemCalibrationResponsePreviousParameters;
  new_parameters?: ItemCalibrationResponseNewParameters;
  fit_statistics?: ItemCalibrationResponseFitStatistics;
  /** Number of responses used */
  sample_size?: number;
  calibrated_at?: string;
}
