/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { ItemCalibrationRequestResponsesItem } from "./itemCalibrationRequestResponsesItem";

export interface ItemCalibrationRequest {
  /** Item to calibrate */
  item_id: string;
  responses: ItemCalibrationRequestResponsesItem[];
  /** Force recalibration even if item has parameters */
  force_recalibrate?: boolean;
}
