/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type ItemCalibrationResponseNewParameters = {
  /** Item difficulty (b parameter) */
  difficulty: number;
  /** Item discrimination (a parameter) */
  discrimination: number;
  /** Guessing parameter (c parameter) */
  guessing: number;
};
