/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { ListAssessmentsAssessmentType } from "./listAssessmentsAssessmentType";

export type ListAssessmentsParams = {
  tenant_id?: string;
  learner_id?: string;
  assessment_type?: ListAssessmentsAssessmentType;
  /**
   * @maximum 100
   */
  limit?: number;
  offset?: number;
};
