/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export type NextQuestionResponseItemType =
  (typeof NextQuestionResponseItemType)[keyof typeof NextQuestionResponseItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NextQuestionResponseItemType = {
  multiple_choice: "multiple_choice",
  true_false: "true_false",
  short_answer: "short_answer",
} as const;
