/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { NextQuestionResponseOptionsItem } from "./nextQuestionResponseOptionsItem";
import type { NextQuestionResponseItemType } from "./nextQuestionResponseItemType";

export interface NextQuestionResponse {
  session_id?: string;
  item_id?: string;
  /** Question content */
  question_text?: string;
  options?: NextQuestionResponseOptionsItem[];
  item_type?: NextQuestionResponseItemType;
  /** Item difficulty parameter */
  difficulty?: number;
  /** Expected information at current theta */
  information?: number;
  /** Whether this is the final question */
  is_complete?: boolean;
}
