/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface QuestionAnalytics {
  question_id?: string;
  response_time_ms?: number;
  is_correct?: boolean;
  difficulty_level?: number;
  discrimination_index?: number;
}
