/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */

export interface ResponseResult {
  id?: string;
  question_id?: string;
  is_correct?: boolean;
  score?: number;
  feedback?: string;
  next_question_id?: string;
}
