/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Assessment Service API
 * Assessment service for educational evaluations with IRT-ready analytics
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAssessmentRequestStatus } from "./updateAssessmentRequestStatus";
import type { AssessmentQuestion } from "./assessmentQuestion";
import type { UpdateAssessmentRequestMetadata } from "./updateAssessmentRequestMetadata";

export interface UpdateAssessmentRequest {
  title?: string;
  description?: string;
  status?: UpdateAssessmentRequestStatus;
  questions?: AssessmentQuestion[];
  metadata?: UpdateAssessmentRequestMetadata;
}
