/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type CreateModelBindingRequestCapabilitiesItem =
  (typeof CreateModelBindingRequestCapabilitiesItem)[keyof typeof CreateModelBindingRequestCapabilitiesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateModelBindingRequestCapabilitiesItem = {
  text_generation: "text_generation",
  code_completion: "code_completion",
  math_solving: "math_solving",
  creative_writing: "creative_writing",
} as const;
