/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLearnerRequestInitialPersonaPersonalityTraits } from "./createLearnerRequestInitialPersonaPersonalityTraits";

export type CreateLearnerRequestInitialPersona = {
  personality_traits?: CreateLearnerRequestInitialPersonaPersonalityTraits;
  communication_style?: string;
  learning_approach?: string;
};
