/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLearnerRequestLearningPreferences } from "./createLearnerRequestLearningPreferences";
import type { CreateLearnerRequestInitialPersona } from "./createLearnerRequestInitialPersona";

export interface CreateLearnerRequest {
  tenant_id: string;
  user_id: string;
  name: string;
  grade_level: string;
  learning_preferences?: CreateLearnerRequestLearningPreferences;
  initial_persona?: CreateLearnerRequestInitialPersona;
}
