/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { CreateModelBindingRequestProvider } from "./createModelBindingRequestProvider";
import type { CreateModelBindingRequestCapabilitiesItem } from "./createModelBindingRequestCapabilitiesItem";

export interface CreateModelBindingRequest {
  provider: CreateModelBindingRequestProvider;
  model_name: string;
  endpoint_url?: string;
  api_key_ref?: string;
  is_default?: boolean;
  capabilities?: CreateModelBindingRequestCapabilitiesItem[];
}
