/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type GetLearnerProgressTimeframe =
  (typeof GetLearnerProgressTimeframe)[keyof typeof GetLearnerProgressTimeframe];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLearnerProgressTimeframe = {
  week: "week",
  month: "month",
  quarter: "quarter",
  year: "year",
} as const;
