/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { LearnerProgressSubjectProgress } from "./learnerProgressSubjectProgress";
import type { LearnerProgressLevelProgressionItem } from "./learnerProgressLevelProgressionItem";
import type { LearnerProgressRecentActivitiesItem } from "./learnerProgressRecentActivitiesItem";

export interface LearnerProgress {
  learner_id?: string;
  timeframe?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  overall_progress?: number;
  subject_progress?: LearnerProgressSubjectProgress;
  level_progression?: LearnerProgressLevelProgressionItem[];
  recent_activities?: LearnerProgressRecentActivitiesItem[];
  strengths?: string[];
  growth_areas?: string[];
}
