/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type LearnerProgressRecentActivitiesItem = {
  activity_type?: string;
  timestamp?: string;
  performance?: number;
};
