/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { LearnerCurrentLevel } from "./learnerCurrentLevel";
import type { LearnerLearningPreferences } from "./learnerLearningPreferences";
import type { PrivateBrain } from "./privateBrain";
import type { ModelBinding } from "./modelBinding";

export interface Learner {
  id?: string;
  tenant_id?: string;
  user_id?: string;
  name?: string;
  grade_level?: string;
  current_level?: LearnerCurrentLevel;
  learning_preferences?: LearnerLearningPreferences;
  private_brain?: PrivateBrain;
  model_bindings?: ModelBinding[];
  created_at?: string;
  updated_at?: string;
}
