/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type ModelBindingProvider =
  (typeof ModelBindingProvider)[keyof typeof ModelBindingProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelBindingProvider = {
  openai: "openai",
  anthropic: "anthropic",
  google: "google",
  custom: "custom",
} as const;
