/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { ModelBindingProvider } from "./modelBindingProvider";
import type { ModelBindingCapabilitiesItem } from "./modelBindingCapabilitiesItem";

export interface ModelBinding {
  id?: string;
  learner_id?: string;
  provider?: ModelBindingProvider;
  model_name?: string;
  endpoint_url?: string;
  api_key_ref?: string;
  is_default?: boolean;
  capabilities?: ModelBindingCapabilitiesItem[];
  created_at?: string;
  updated_at?: string;
}
