/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type PrivateBrainCommunicationStyle =
  (typeof PrivateBrainCommunicationStyle)[keyof typeof PrivateBrainCommunicationStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivateBrainCommunicationStyle = {
  formal: "formal",
  casual: "casual",
  encouraging: "encouraging",
  analytical: "analytical",
} as const;
