/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type PrivateBrainLearningApproach =
  (typeof PrivateBrainLearningApproach)[keyof typeof PrivateBrainLearningApproach];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivateBrainLearningApproach = {
  visual: "visual",
  auditory: "auditory",
  kinesthetic: "kinesthetic",
  mixed: "mixed",
} as const;
