/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { PrivateBrainPersonalityTraits } from "./privateBrainPersonalityTraits";
import type { PrivateBrainCommunicationStyle } from "./privateBrainCommunicationStyle";
import type { PrivateBrainLearningApproach } from "./privateBrainLearningApproach";

export interface PrivateBrain {
  id?: string;
  learner_id?: string;
  persona_name?: string;
  personality_traits?: PrivateBrainPersonalityTraits;
  communication_style?: PrivateBrainCommunicationStyle;
  learning_approach?: PrivateBrainLearningApproach;
  strengths?: string[];
  growth_areas?: string[];
  created_at?: string;
  updated_at?: string;
}
