/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type PrivateBrainPersonalityTraits = {
  /**
   * @minimum 0
   * @maximum 1
   */
  curiosity?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  patience?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  encouragement?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  creativity?: number;
};
