/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type UpdateLearnerRequestCurrentLevel =
  (typeof UpdateLearnerRequestCurrentLevel)[keyof typeof UpdateLearnerRequestCurrentLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLearnerRequestCurrentLevel = {
  beginner: "beginner",
  easy: "easy",
  moderate: "moderate",
  challenging: "challenging",
  advanced: "advanced",
} as const;
