/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */

export type UpdateLevelRequestPerformanceData = {
  current_score?: number;
  consecutive_correct?: number;
  consecutive_incorrect?: number;
};
