/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLevelRequestLevel } from "./updateLevelRequestLevel";
import type { UpdateLevelRequestPerformanceData } from "./updateLevelRequestPerformanceData";

export interface UpdateLevelRequest {
  level: UpdateLevelRequestLevel;
  reason: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
  performance_data?: UpdateLevelRequestPerformanceData;
  temporary?: boolean;
}
