/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Learner Service API
 * Learner management service with private brain personas and level management
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLearnerRequestCurrentLevel } from "./updateLearnerRequestCurrentLevel";
import type { UpdateLearnerRequestLearningPreferences } from "./updateLearnerRequestLearningPreferences";

export interface UpdateLearnerRequest {
  name?: string;
  grade_level?: string;
  current_level?: UpdateLearnerRequestCurrentLevel;
  learning_preferences?: UpdateLearnerRequestLearningPreferences;
}
