# Prometheus configuration for aivo-virtual-brains

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "aivo-dev"
    environment: "development"

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # OpenTelemetry Collector metrics
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888", "otel-collector:8889"]
    scrape_interval: 10s

  # Kong API Gateway metrics
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Redis metrics (via redis_exporter if added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # PostgreSQL metrics (via postgres_exporter if added)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Apollo Router metrics (if exposed)
  - job_name: "apollo-router"
    static_configs:
      - targets: ["apollo-router:4000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # OpenSearch metrics
  - job_name: "opensearch"
    static_configs:
      - targets: ["opensearch:9200"]
    metrics_path: "/_prometheus/metrics"
    scrape_interval: 30s
