apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: learnernamespaces.learner.aivo.com
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
spec:
  group: learner.aivo.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              learnerID:
                type: string
                description: "Unique identifier for the learner"
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    default: "100m"
                  memory:
                    type: string
                    default: "128Mi"
                  storage:
                    type: string
                    default: "1Gi"
              networkPolicy:
                type: boolean
                default: true
                description: "Enable network isolation"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Active", "Terminating"]
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
  scope: Namespaced
  names:
    plural: learnernamespaces
    singular: learnernamespace
    kind: LearnerNamespace
    shortNames:
    - lns