apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "learner-ns-operator.serviceAccountName" . }}
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "learner-ns-operator.fullname" . }}-manager-role
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - limitranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learner.aivo.com
  resources:
  - learnernamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learner.aivo.com
  resources:
  - learnernamespaces/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "learner-ns-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "learner-ns-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "learner-ns-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}