{{- if .Values.health.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "learner-ns-operator.fullname" . }}-health
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: health
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.health.port }}
    targetPort: health
    protocol: TCP
    name: health
  selector:
    {{- include "learner-ns-operator.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "learner-ns-operator.fullname" . }}-metrics
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "learner-ns-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "learner-ns-operator.selectorLabels" . | nindent 4 }}
{{- end }}
