/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Notification Service API
 * Real-time notification service with WebSocket hub, push subscriptions, and daily digest functionality.

## Features
- **WebSocket Hub**: Real-time notification delivery via WebSocket connections
- **Push Subscriptions**: Browser push notifications with Web Push API
- **Daily Digest**: Automated daily summary notifications
- **Multi-channel Delivery**: Support for WebSocket, push, email, and in-app notifications
- **Real-time Collaboration**: 1-to-N message fanout for collaborative features

## Authentication
All endpoints require JWT authentication via the `Authorization` header:
```
Authorization: Bearer <jwt_token>
```

## WebSocket Connection
Connect to real-time notifications via WebSocket:
```
wss://api.aivo.ai/notification-svc/ws/notify?token=<jwt_token>
```

 * OpenAPI spec version: 1.0.0
 */
import type { NotificationType } from "./notificationType";

export type GetApiV1NotificationsParams = {
  /**
   * Maximum number of notifications to return
   * @maximum 100
   */
  limit?: number;
  /**
   * Number of notifications to skip
   */
  offset?: number;
  /**
   * Return only unread notifications
   */
  unread_only?: boolean;
  /**
   * Filter by notification type
   */
  notification_type?: NotificationType;
};
