/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Notification Service API
 * Real-time notification service with WebSocket hub, push subscriptions, and daily digest functionality.

## Features
- **WebSocket Hub**: Real-time notification delivery via WebSocket connections
- **Push Subscriptions**: Browser push notifications with Web Push API
- **Daily Digest**: Automated daily summary notifications
- **Multi-channel Delivery**: Support for WebSocket, push, email, and in-app notifications
- **Real-time Collaboration**: 1-to-N message fanout for collaborative features

## Authentication
All endpoints require JWT authentication via the `Authorization` header:
```
Authorization: Bearer <jwt_token>
```

## WebSocket Connection
Connect to real-time notifications via WebSocket:
```
wss://api.aivo.ai/notification-svc/ws/notify?token=<jwt_token>
```

 * OpenAPI spec version: 1.0.0
 */

export * from "./digestSubscription";
export * from "./digestSubscriptionAllOf";
export * from "./digestSubscriptionUpdate";
export * from "./digestSubscriptionUpdateFrequency";
export * from "./getApiV1NotificationsParams";
export * from "./getApiV1NotificationsStatsParams";
export * from "./getHealth200";
export * from "./getWsNotifyParams";
export * from "./getWsStatus200";
export * from "./notificationCreate";
export * from "./notificationCreateContextData";
export * from "./notificationCreateMetadata";
export * from "./notificationListResponse";
export * from "./notificationPriority";
export * from "./notificationResponse";
export * from "./notificationResponseMetadata";
export * from "./notificationStats";
export * from "./notificationStatsNotificationsByType";
export * from "./notificationStatus";
export * from "./notificationType";
export * from "./postApiV1NotificationsReadAll200";
export * from "./pushSubscriptionCreate";
export * from "./pushSubscriptionCreateDeviceInfo";
export * from "./pushSubscriptionCreateNotificationPreferences";
export * from "./pushSubscriptionResponse";
