/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Notification Service API
 * Real-time notification service with WebSocket hub, push subscriptions, and daily digest functionality.

## Features
- **WebSocket Hub**: Real-time notification delivery via WebSocket connections
- **Push Subscriptions**: Browser push notifications with Web Push API
- **Daily Digest**: Automated daily summary notifications
- **Multi-channel Delivery**: Support for WebSocket, push, email, and in-app notifications
- **Real-time Collaboration**: 1-to-N message fanout for collaborative features

## Authentication
All endpoints require JWT authentication via the `Authorization` header:
```
Authorization: Bearer <jwt_token>
```

## WebSocket Connection
Connect to real-time notifications via WebSocket:
```
wss://api.aivo.ai/notification-svc/ws/notify?token=<jwt_token>
```

 * OpenAPI spec version: 1.0.0
 */
import type { NotificationType } from "./notificationType";
import type { NotificationPriority } from "./notificationPriority";
import type { NotificationCreateMetadata } from "./notificationCreateMetadata";
import type { NotificationCreateContextData } from "./notificationCreateContextData";

export interface NotificationCreate {
  /**
   * Notification title
   * @maxLength 500
   */
  title: string;
  /**
   * Notification message body
   * @minLength 1
   */
  message: string;
  notification_type: NotificationType;
  priority?: NotificationPriority;
  /** Delivery channels for this notification */
  channels?: string[];
  /** Additional notification metadata */
  metadata?: NotificationCreateMetadata;
  /** Related entity data */
  context_data?: NotificationCreateContextData;
  /**
   * URL for notification action
   * @maxLength 1000
   */
  action_url?: string;
  /** When to deliver the notification */
  scheduled_at?: string;
}
