/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AIVO Notification Service API
 * Real-time notification service with WebSocket hub, push subscriptions, and daily digest functionality.

## Features
- **WebSocket Hub**: Real-time notification delivery via WebSocket connections
- **Push Subscriptions**: Browser push notifications with Web Push API
- **Daily Digest**: Automated daily summary notifications
- **Multi-channel Delivery**: Support for WebSocket, push, email, and in-app notifications
- **Real-time Collaboration**: 1-to-N message fanout for collaborative features

## Authentication
All endpoints require JWT authentication via the `Authorization` header:
```
Authorization: Bearer <jwt_token>
```

## WebSocket Connection
Connect to real-time notifications via WebSocket:
```
wss://api.aivo.ai/notification-svc/ws/notify?token=<jwt_token>
```

 * OpenAPI spec version: 1.0.0
 */
import type { PushSubscriptionCreateDeviceInfo } from "./pushSubscriptionCreateDeviceInfo";
import type { PushSubscriptionCreateNotificationPreferences } from "./pushSubscriptionCreateNotificationPreferences";

export interface PushSubscriptionCreate {
  /**
   * Push service endpoint URL
   * @maxLength 1000
   */
  endpoint: string;
  /**
   * P-256 ECDH public key for encryption
   * @maxLength 255
   */
  p256dh_key: string;
  /**
   * Authentication secret for encryption
   * @maxLength 255
   */
  auth_key: string;
  /**
   * Browser user agent string
   * @maxLength 1000
   */
  user_agent?: string;
  /** Additional device information */
  device_info?: PushSubscriptionCreateDeviceInfo;
  /** User notification preferences for this device */
  notification_preferences?: PushSubscriptionCreateNotificationPreferences;
}
