# Default values for learner-ns-operator
# This is a YAML-formatted file.

global:
  imageRegistry: ""
  imagePullSecrets: []

platform:
  enabled: true

replicaCount: 1

image:
  repository: aivo/learner-ns-operator
  tag: "1.0.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "learner-ns-operator"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "learner-ns-operator"

rbac:
  create: true

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "learner-ns-operator"
  vault.hashicorp.com/agent-inject-secret-config: "secret/data/learner-ns-operator"
  vault.hashicorp.com/agent-inject-template-config: |
    {{- with secret "secret/data/learner-ns-operator" -}}
    VAULT_TOKEN={{ .Data.data.vault_token }}
    {{- end }}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - learner-ns-operator
        topologyKey: kubernetes.io/hostname

# Operator-specific configuration
operator:
  # Namespace where the operator will be deployed
  namespace: aivo-system
  
  # Logging level
  logLevel: INFO
  
  # Default resource quotas for learner namespaces
  defaultResourceQuota:
    cpu: "2"
    memory: "4Gi"
    storage: "10Gi"
    pods: 10
  
  # Default network policy settings
  defaultNetworkPolicy:
    egressDeny: true
    allowedNamespaces:
      - "aivo-system"
      - "aivo-shared"
  
  # Default Vault role for learners
  defaultVaultRole: "learner-default"
  
  # Webhook configuration (for future use)
  webhook:
    enabled: false
    port: 9443
    certManager:
      enabled: false

# Health and monitoring
health:
  enabled: true
  port: 8080
  path: /healthz

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels:
      prometheus: aivo-monitoring

# Custom Resource Definition
crd:
  # Whether to install the CRD (should be true for first install)
  install: true
  # Whether to upgrade the CRD (should be false to avoid conflicts)
  upgrade: false
