apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: aivo-platform
    aivo.dev/component: progressive-delivery
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/aivo/virtual-brains.git
    targetRevision: HEAD
    path: infra/rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: aivo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argo-rollouts
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progressive-delivery-configs
  namespace: argocd
  labels:
    app.kubernetes.io/name: progressive-delivery-configs
    app.kubernetes.io/part-of: aivo-platform
    aivo.dev/component: rollout-configs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://github.com/aivo/virtual-brains.git
      targetRevision: HEAD
      path: infra/rollouts
      directory:
        include: |
          analysis-templates.yaml
          canary-rollouts.yaml
          bluegreen-rollouts.yaml
          services.yaml
          ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aivo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/template/spec/containers/0/image
        - /status
    - group: argoproj.io
      kind: AnalysisRun
      jsonPointers:
        - /status
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-project
    app.kubernetes.io/part-of: aivo-platform
spec:
  description: Platform infrastructure and shared services
  sourceRepos:
    - https://github.com/aivo/virtual-brains.git
    - https://argoproj.github.io/argo-helm
    - https://kubernetes.github.io/ingress-nginx
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionWebhook
    - group: admissionregistration.k8s.io
      kind: MutatingAdmissionWebhook
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: argoproj.io
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: monitoring.coreos.com
      kind: "*"
    - group: cert-manager.io
      kind: "*"
  roles:
    - name: platform-admin
      description: Full access to platform resources
      policies:
        - p, proj:platform:platform-admin, applications, *, platform/*, allow
        - p, proj:platform:platform-admin, repositories, *, *, allow
        - p, proj:platform:platform-admin, certificates, *, *, allow
      groups:
        - aivo:platform-team
    - name: developer
      description: Limited access for developers
      policies:
        - p, proj:platform:developer, applications, get, platform/*, allow
        - p, proj:platform:developer, applications, sync, platform/*, allow
        - p, proj:platform:developer, logs, get, platform/*, allow
      groups:
        - aivo:developers
  syncWindows:
    - kind: allow
      schedule: "0 9-17 * * 1-5"
      duration: 8h
      applications:
        - "*"
      manualSync: true
    - kind: deny
      schedule: "0 18-8 * * *"
      duration: 14h
      applications:
        - "*"
      manualSync: false
      timeZone: UTC
