name: ci-python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.3 || pip install --user poetry==1.8.3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install deps (Poetry)
        if: ${{ hashFiles('**/pyproject.toml') != '' }}
        run: |
          poetry install --no-interaction --no-ansi --no-root

      - name: Ruff
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pip install ruff==0.5.7
          ruff --version
          ruff .

      - name: Mypy (strict)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pip install mypy==1.10.0
          mypy --strict .

      - name: Pytest
        if: ${{ hashFiles('**/tests/**/*.py') != '' }}
        run: |
          pip install pytest==8.2.2
          pytest -q

      - name: pip-audit (strict)
        if: ${{ hashFiles('**/pyproject.toml') != '' || hashFiles('**/requirements*.txt') != '' }}
        run: |
          pip install pip-audit==2.7.3
          if [ -f requirements.txt ]; then \
            pip-audit -r requirements.txt --strict; \
          elif [ -f pyproject.toml ]; then \
            pip-audit --strict; \
          else \
            echo 'No dependency manifest found'; \
          fi

      - name: Docker build (noop if no Dockerfile)
        if: ${{ hashFiles('**/Dockerfile') != '' }}
        run: |
          docker build -t local/python-app .

      - name: Trivy image scan (noop)
        if: ${{ hashFiles('**/Dockerfile') != '' }}
        run: |
          sudo apt-get update && sudo apt-get install -y wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy
          trivy image --severity HIGH,CRITICAL --exit-code 1 --no-progress local/python-app || (echo "Image vulnerabilities found" && exit 1)
