name: sbom-sign

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      - name: Generate SBOMs (SPDX & CycloneDX)
        run: |
          syft dir:. -o spdx-json=sbom.spdx.json,cyclonedx-json=sbom.cdx.json

      - name: Setup Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Keyless sign SBOMs with Cosign
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob --yes --output-signature sbom.spdx.sig sbom.spdx.json
          cosign sign-blob --yes --output-signature sbom.cdx.sig sbom.cdx.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-signatures
          path: |
            sbom.spdx.json
            sbom.cdx.json
            sbom.spdx.sig
            sbom.cdx.sig
