name: Stage-2 Verification

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  stage2-verification:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aivo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      opensearch:
        image: opensearchproject/opensearch:2
        env:
          discovery.type: single-node
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: admin
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.4"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Build services
        run: pnpm run build

      - name: Start services
        run: |
          pnpm run compose:up
          sleep 30 # Wait for services to start

      - name: Health check
        run: pnpm run health:check

      - name: Run Stage-2 verification
        run: pnpm run verify-stage2
        env:
          BASE_URL: http://localhost
          CI: true

      - name: Run performance tests
        run: pnpm run test:performance
        env:
          BASE_URL: http://localhost

      - name: Upload verification report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: stage2-verification-report
          path: stage2-verification-report.json

      - name: Cleanup
        if: always()
        run: pnpm run compose:down

  integration-tests:
    runs-on: ubuntu-latest
    needs: stage2-verification

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.4"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run integration tests
        run: pnpm run test:integration

      - name: Security scan
        run: pnpm run sec:all
